// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    AppLink: typeof import('./components/AppLink.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    BlogList: typeof import('./components/BlogList.vue')['default']
    ButtonNav: typeof import('./components/ButtonNav.vue')['default']
    CategoryList: typeof import('./components/CategoryList.vue')['default']
    Comment: typeof import('./components/Comment.vue')['default']
    Discussion: typeof import('./components/icons/Discussion.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Links: typeof import('./components/Links.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Nutshell: typeof import('./components/Nutshell.vue')['default']
    Project: typeof import('./components/Project.vue')['default']
    ProjectList: typeof import('./components/ProjectList.vue')['default']
    Right: typeof import('./components/icons/Right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section.vue')['default']
    SendMessage: typeof import('./components/SendMessage.vue')['default']
    TagList: typeof import('./components/TagList.vue')['default']
    TimeIcon: typeof import('./components/icons/TimeIcon.vue')['default']
    WelcomeMsg: typeof import('./components/WelcomeMsg.vue')['default']
  }
}
